name: dice_flutter_v1
description: "This is a Simple Dice Flutter app. I have tried to bring some functionality to a flutter app for first time."
publish_to: "none"
homepage: https://github.com/KASRA10/dice_flutter_version_one.git
issue_tracker: https://github.com/KASRA10/dice_flutter_version_one.git
documentation: https://github.com/KASRA10/dice_flutter_version_one.git
repository: https://github.com/KASRA10/dice_flutter_version_one.git

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/

  fonts:
    - family: PTSans
      fonts:
        - asset: lib/fonts/PTSans.ttf
          style: normal
